# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_transferencia.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Janela3(object):
    def setupUi(self, Janela3):
        Janela3.setObjectName("Janela3")
        Janela3.resize(414, 281)
        Janela3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(Janela3)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 10, 221, 51))
        self.label.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.inputContaTrans = QtWidgets.QLineEdit(self.centralwidget)
        self.inputContaTrans.setGeometry(QtCore.QRect(210, 100, 161, 20))
        self.inputContaTrans.setObjectName("inputContaTrans")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(210, 80, 121, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(170, 130, 71, 16))
        self.label_4.setObjectName("label_4")
        self.inputQuantiaTrans = QtWidgets.QLineEdit(self.centralwidget)
        self.inputQuantiaTrans.setGeometry(QtCore.QRect(120, 150, 161, 20))
        self.inputQuantiaTrans.setObjectName("inputQuantiaTrans")
        self.button_Transferencia = QtWidgets.QPushButton(self.centralwidget)
        self.button_Transferencia.setGeometry(QtCore.QRect(150, 180, 101, 31))
        self.button_Transferencia.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.button_Transferencia.setObjectName("button_Transferencia")
        self.label_ErrorTrans = QtWidgets.QLabel(self.centralwidget)
        self.label_ErrorTrans.setGeometry(QtCore.QRect(50, 220, 321, 31))
        self.label_ErrorTrans.setText("")
        self.label_ErrorTrans.setObjectName("label_ErrorTrans")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 141, 16))
        self.label_2.setObjectName("label_2")
        self.inputNomeTrans = QtWidgets.QLineEdit(self.centralwidget)
        self.inputNomeTrans.setGeometry(QtCore.QRect(30, 100, 151, 20))
        self.inputNomeTrans.setObjectName("inputNomeTrans")
        Janela3.setCentralWidget(self.centralwidget)

        self.retranslateUi(Janela3)
        QtCore.QMetaObject.connectSlotsByName(Janela3)

    def retranslateUi(self, Janela3):
        _translate = QtCore.QCoreApplication.translate
        Janela3.setWindowTitle(_translate("Janela3", "TRANSFERENCIA BANCARIA"))
        self.label.setText(_translate("Janela3", "TRANSFERÊNCIA"))
        self.label_3.setText(_translate("Janela3", "CONTA do destinatario:"))
        self.label_4.setText(_translate("Janela3", "QUANTIA:"))
        self.button_Transferencia.setText(_translate("Janela3", "TRANSFERIR"))
        self.label_2.setText(_translate("Janela3", "Nome (ID) do destinatario:"))
