# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_msg.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mensagemDeposito(object):
    def setupUi(self, mensagemDeposito):
        mensagemDeposito.setObjectName("mensagemDeposito")
        mensagemDeposito.resize(290, 217)
        mensagemDeposito.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.centralwidget = QtWidgets.QWidget(mensagemDeposito)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_Mensagem = QtWidgets.QLabel(self.centralwidget)
        self.label_Mensagem.setStyleSheet("font: 75 16pt \"Reckoner Bold\";")
        self.label_Mensagem.setText("")
        self.label_Mensagem.setObjectName("label_Mensagem")
        self.gridLayout.addWidget(self.label_Mensagem, 0, 0, 1, 1)
        mensagemDeposito.setCentralWidget(self.centralwidget)

        self.retranslateUi(mensagemDeposito)
        QtCore.QMetaObject.connectSlotsByName(mensagemDeposito)

    def retranslateUi(self, mensagemDeposito):
        _translate = QtCore.QCoreApplication.translate
        mensagemDeposito.setWindowTitle(_translate("mensagemDeposito", "DEPOSITADO!"))
