# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(622, 476)
        MainWindow.setStyleSheet("background-color: rgb(7, 160, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, -10, 301, 231))
        self.label.setStyleSheet("font: 20pt \"Grand Aventure Text\";\n"
"font: 48pt \"Grand Aventure Text\";")
        self.label.setObjectName("label")
        self.inputNomeBancario = QtWidgets.QLineEdit(self.centralwidget)
        self.inputNomeBancario.setGeometry(QtCore.QRect(190, 190, 241, 31))
        self.inputNomeBancario.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.inputNomeBancario.setObjectName("inputNomeBancario")
        self.inputContaBanco = QtWidgets.QLineEdit(self.centralwidget)
        self.inputContaBanco.setGeometry(QtCore.QRect(190, 310, 241, 31))
        self.inputContaBanco.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.inputContaBanco.setObjectName("inputContaBanco")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 170, 131, 21))
        self.label_2.setStyleSheet("font: 18pt \"Grand Aventure Text\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(220, 270, 211, 31))
        self.label_3.setStyleSheet("font: 18pt \"Grand Aventure Text\";")
        self.label_3.setObjectName("label_3")
        self.buttonLogin = QtWidgets.QPushButton(self.centralwidget)
        self.buttonLogin.setGeometry(QtCore.QRect(190, 360, 101, 51))
        self.buttonLogin.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.buttonLogin.setObjectName("buttonLogin")
        self.label_Error = QtWidgets.QLabel(self.centralwidget)
        self.label_Error.setGeometry(QtCore.QRect(120, 420, 401, 41))
        self.label_Error.setStyleSheet("font: 87 14pt \"Arial Black\";")
        self.label_Error.setText("")
        self.label_Error.setObjectName("label_Error")
        self.buttonRegister = QtWidgets.QPushButton(self.centralwidget)
        self.buttonRegister.setGeometry(QtCore.QRect(320, 360, 111, 51))
        self.buttonRegister.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.buttonRegister.setObjectName("buttonRegister")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BANCO GUEEG GAMING"))
        self.label.setText(_translate("MainWindow", "LOGIN BANCÁRIO"))
        self.label_2.setText(_translate("MainWindow", "NOME:"))
        self.label_3.setText(_translate("MainWindow", "CONTA(APENAS NUMEROS):"))
        self.buttonLogin.setText(_translate("MainWindow", "LOGIN!"))
        self.buttonRegister.setText(_translate("MainWindow", "REGISTRAR!"))
